name: CI-test-lint

on:
  push:
    branches: 
      - "modul4/api"
      - "modul5/**"
      - "modul6/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
     
      - name: Install modules
        run: npm install

      - name: Unit test
        run: npm run test
        
      - name: Eslint code
        run: npm run lint
